---
- name: install python3-setuptools
  shell: sudo apt-get -y install python3-setuptools
  become: yes

- name: install pip
  shell: sudo easy_install3 pip
  become: yes

- name: Install Django
  become: yes
  pip: 
    name:  "{{ item }}"
    executable: pip3
  with_items:
    - django
    - djangorestframework
    - PyMySQL
    - django-rest-swagger

- name: create folders
  become: yes
  file:
    path: "{{app_path}}{{app_name}}/static"
    state: directory
    mode: 0755

- name: create folders
  become: yes
  file:
    path: "{{app_path}}{{app_name}}/static/admin"
    state: directory
    mode: 0755



- name: create folders
  become: yes
  file:
    path: "{{app_path}}{{app_name}}/static/admin"
    state: directory
    mode: 0755



- name: create folders
  become: yes
  file:
    path: "{{app_path}}{{app_name}}/media"
    state: directory
    mode: 0755
...

