---
- name: install python3-setuptools
  shell: sudo apt-get -y install python3-setuptools
  become: yes

- name: install pip
  shell: sudo easy_install3 pip
  become: yes

- name: install virtualEnv
  shell: sudo pip install virtualenv
  become: yes

- name: create virtualEnv
  shell: virtualenv -p /usr/bin/python3 "{{ project_path }}"

- name: Install Django
  become: yes
  pip: name="{{ item }}"
  virtualenv: "{{ project_path }}"
  with_items:
    - django

- name: create folders
  file:
    path: "{{app_path}}{{app_name}}/static"
    state: directory
    mode: 0755

- name: create folders
  file:
    path: "{{app_path}}{{app_name}}/media"
    state: directory
    mode: 0755
...

